#!/bin/sh

# This script prints a colorized Gentoo logo. It uses escape sequences to
# avoid additional dependencies and was intended to be used inside the
# Linux console running a simple shell.

# Prints the given error messages and terminates the program with an error
# message.
die()
{
  echo "error: $@" >&2
  exit 1
}

# Asserts that the given color code is valid.
#
# $1 A color like "0;30", code without any escape sequences.
assert_color()
{
  echo -n "$1" | grep -E '^(0|[01];[34][0-9])$' >&/dev/null ||
    die "invalid color: $1"
}

# This function repeats a string and takes two arguments:
#
# $1 The string that should be repeated.
# $2 The repetition count. Negative values will be ignored.
repeat_string()
{
  test $2 -gt 0 && for i in `seq $2`; do echo -n "$1"; done
}

# Process arguments.
test $# -lt 4 || die "too many arguments"
for arg; do
  if [[ "$arg" == "--help" ]]; then
    echo "Usage: print-gentoo-splash [COLORS]..."
    echo "Prints a colorized Gentoo logo."
    echo
    echo "This script takes up to 3 color codes like e.g. \"1;34\","
    echo "specifying a dark, a medium and a bright color. The first"
    echo "argument may also specify one of the colors listed below, in"
    echo "which case the last two arguments will be ignored."
    echo "  * red"
    echo "  * green"
    echo "  * yellow"
    echo "  * blue"
    echo "  * cyan"
    echo "  * white"
    echo "  * grey"
    echo "  * magenta (default)"
    exit
  fi
done

case "$1" in
  red)     dark="0;31" medium="1;31" bright="1;37";;
  green)   dark="0;32" medium="1;32" bright="1;37";;
  yellow)  dark="0;33" medium="1;33" bright="1;37";;
  blue)    dark="0;34" medium="1;34" bright="1;37";;
  cyan)    dark="0;36" medium="1;36" bright="1;37";;
  white)   dark="1;30" medium="0;37" bright="1;37";;
  grey)    dark="1;30" medium="0;37" bright="0;37";;
  magenta) dark="0;35" medium="1;35" bright="1;37";;
  *)
    test -n "$1" && dark="$1"   || dark="0;35"
    test -n "$2" && medium="$2" || medium="1;35"
    test -n "$3" && bright="$3" || bright="1;37";;
esac

assert_color "$dark"
assert_color "$medium"
assert_color "$bright"

# Setup some variables.
LINES=$(stty size | grep -oE '^\S+')
COLUMNS=$(stty size | grep -oE '\S+$')
left_padding=$(repeat_string " " $(($COLUMNS/2 - 16)))
vertical_padding=$(repeat_string "\n" $(($LINES/2 - 10)))

# Print the Gentoo logo.
clear
echo -en "${vertical_padding}"
echo -e "${left_padding}         \e[${dark}mxdllxdxoxx\e[0m"
echo -e "${left_padding}     \e[${dark}mod\e[${medium}mk\e[${bright}m000XXXKK00\e[${medium}mOOk\e[${dark}mlox\e[0m"
echo -e "${left_padding}    \e[${dark}mo\e[${medium}mO\e[${bright}m0NMMMMMWWNXXKK0\e[${medium}mOkk\e[${dark}mlx\e[0m"
echo -e "${left_padding}  \e[${dark}mo\e[${medium}mO\e[${bright}mKWMMMMMMMMMWWNXKK000\e[${medium}mOkO\e[${dark}mlx\e[0m"
echo -e "${left_padding} \e[${dark}mo\e[${medium}mk\e[${bright}mXMMMMMMMMWNX\e[${medium}mOkk\e[${bright}m0XXK0000\e[${medium}mOkk\e[${dark}mlo\e[0m"
echo -e "${left_padding}\e[${dark}mlx\e[${medium}mO\e[${bright}mNMMMMMMMMW0\e[${medium}mO\e[${dark}mxdocx\e[${bright}mXXK00000\e[${medium}mOOk\e[${dark}mlo\e[0m"
echo -e "${left_padding} \e[${dark}mxcd\e[${medium}mk\e[${bright}mKNWMMMMMMNK0\e[${medium}mkk\e[${bright}m0XXKK000000\e[${medium}mOO\e[${dark}mlo\e[0m"
echo -e "${left_padding} \e[${dark}mlldloo\e[${medium}mOO\e[${bright}m0XWMMMMMMWWNXXKKK000000\e[${dark}mlo\e[0m"
echo -e "${left_padding}    \e[${dark}mloxdl\e[${medium}mOk\e[${bright}mXMMMMMMWWNNXXKKKKKKXW\e[${dark}mdd\e[0m"
echo -e "${left_padding}      \e[${dark}ml\e[${bright}m0\e[${medium}mO\e[${bright}mXMMMMMMMMWWNNXXXXXXNWK\e[${dark}mxlo\e[0m"
echo -e "${left_padding}   \e[${dark}ml\e[${bright}mKKKNMMMMMMMMMWWWNNNNXNNX0\e[${dark}mxoxd\e[0m"
echo -e "${left_padding} \e[${dark}mx\e[${medium}mOO\e[${bright}mKWMMMMMMMMMMWWWNNNNWN0\e[${medium}mk\e[${dark}molxx\e[0m"
echo -e "${left_padding}\e[${dark}mx\e[${medium}mOk\e[${bright}mXWWMMMMMMMWWWWWWWWX0\e[${medium}mk\e[${dark}mooodx\e[0m"
echo -e "${left_padding}\e[${dark}md\e[${medium}mk\e[${bright}m0NNNNNWWWNNNNNWNX0\e[${medium}mk\e[${dark}mdolxo\e[0m"
echo -e "${left_padding}\e[${dark}mlo\e[${medium}mk\e[${bright}mKKXXXXXXXXK0\e[${medium}mOk\e[${dark}mdxxdxo\e[0m"
echo -e "${left_padding}\e[${dark}moxcox\e[${medium}mkkkkkk\e[${dark}mdddddxxxo\e[0m"
echo -e "${left_padding} \e[${dark}mdolxldddddxlddo\e[0m"
echo -e "${left_padding}      \e[${dark}modlo\e[0m"
echo -en "${vertical_padding}"
