#!/bin/bash

set -e
for arg; do
  case "$arg" in
    --help)
      echo "Usage: remove-kernel-residue"
      echo "Removes all kernels and modules, which are not used anymore"
      echo "and do not belong to any package."
      echo
      echo "Takes no arguments other than \"--help\"."
      exit
      ;;
    *)
      echo "invalid argument: \"$arg\", try --help." >&2
      exit 1
      ;;
  esac
done

# This function reads full directory paths from its input stream and
# removes them recursively.
function remove_dirs()
{
  while read dir; do
    echo "Removing $dir/"
    rm -rf "$dir"
  done
}

# Collect all installed and running kernels.
LFS="" kernels=$(uname -r &&
  equery list 'sys-kernel/*' |
  grep -o '[^\/]*-sources-.*$' |
  sed -r 's,^([^-]+)-sources-([^-]+)(.*)$,\2-\1\3,g' |
  sed -r 's,^(.*)-vanilla(-.*)?$,\1,g')

ls -d /usr/src/* | grep -E '^/usr/src/linux-.*$' |
  grep -vxF "$(LFS="" sed -r 's,^,/usr/src/linux-,g' <<< "$kernels")" |
  remove_dirs

ls -d /lib/modules/* |
  grep -vxF "$(LFS="" sed -r 's,^,/lib/modules/,g' <<< "$kernels")" |
  remove_dirs
