#!/bin/bash

# This script updates the entire system, including the kernel and various
# config files. It performs some additional cleanups.
set -e

# Update the system.
emerge --sync
emerge -auDN --with-bdeps=y @world
emerge @preserved-rebuild
revdep-rebuild --ignore
build-kernel --update
etc-update

# Clean up.
emerge -c
eclean-dist --destructive
eclean-pkg --destructive
remove-kernel-residue
fstrim -v /
